### ISSUE TITLE
Réimplémenter le split

### ISSUE THREAD

**Issue by vicdup** [seitrec/Bubulles#2]
A réimplanter

**Comment by Peltierdams** [comment]
Yo, j'aurais juste quelques questions. La fonction split doit gérer le cas d'un virus également ? Et sinon lorsqu'on fait un split avec la space bar, c'est globalement dans une direction précise pour aller bouffer quelqu'un, est-ce que toutes les bubulles du joueur se split ?

**Comment by MelkMerle** [comment]
A priori un virus va faire plein de eject, pas plein de split ? enfin, à réfléchir en effet. Pour ce qui est de la deuxième question, oui, la space bar fait splitter toutes les cellules du joueur
