### ISSUE TITLE
Réimplémenter eat

### ISSUE THREAD

**Issue by vicdup** [seitrec/Bubulles#5]
A reimplanter

**Comment by MelkMerle** [comment]
je m'y mets

**Comment by vicdup** [comment]
Presque bon, il doit juste y avoir un probleme dans les coordonnées, je regarde un peu plus tard...

Je n'ai fais que cell eat food parce que je pense que cell eat cell c'est géré différemment.

**Comment by MelkMerle** [comment]
Bah, cell eat cell c’est pareil, non ? Faut juste qu’on prenne le vecteur de toutes les entités plutôt que celui de juste la bouffe, après on appelle la fonction geteaten (qui, elle, est différente selon que l’on parle d’une cell ou d’une food), puis on efface l’entité du vecteur, comme tu l’as déjà fait dans la fonction.

**Comment by seitrec** [comment]
Après discussions de ce matin:
- CheckCollision parcourt l'esnemble des objets pouvant entrer en collision
- Pour chaque collision, checkCollision appelle la suite des évènements (eat etc..)
